version: '3.8'

services:

  whoops:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "4000:4000"
    networks:
      - external_network
      - app_network

  whoops-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app_network


networks:
  app_network:
    driver: overlay
  external_network:
    name: briefbill_app_network
    external: true
